
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { SpeedInsights } from '@vercel/speed-insights/next';
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Joyn-Digital',
  description: 'Generated by create next app',  
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en" className='scroll-smooth'>
              <Head>
          
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon.ico" />
        </Head>
      
      <body className={inter.className} >
     
        <Navbar />
     
        {children}
        <Footer />
        <SpeedInsights />
        </body>
    </html>
  )
}
